/**
 * গেট ডেটাসেট বিল্ডার (npm run build:gates)
 *
 * 1) দুটি Overpass রপ্তানি থেকে মসজিদের গেট বের করে `GATES_OSM` (TS) তৈরি করে।
 * 2) ক্লায়েন্ট-সাইড ডেটা সোর্সের জন্য `lib/data/gates-osm.generated.ts` লেখে —
 *    এটিই "আমার কাছে"-র গেট বিভাগ ও গেট-সার্চ খায়।
 *
 * (আগের PMTiles/tippecanoe ধাপটি বাদ — ভেক্টর-টাইল গেট লেয়ার সরানোর পর
 * কেউ আর `public/tiles/gates.pmtiles` পড়ে না।)
 *
 * এখানে একমাত্র ফাইল যেটি ডিস্কে I/O করে; transform.mjs সম্পূর্ণ বিশুদ্ধ।
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { extractGatesFromOverpass, toGate } from "./transform.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..", "..");

const GENERATED_TS = join(ROOT, "lib", "data", "gates-osm.generated.ts");
const GENERATED_HEADER =
  "// GENERATED by `npm run build:gates` — do not edit. Regenerate by running the script.";

function loadOverpass(relPath) {
  const raw = readFileSync(join(ROOT, relPath), "utf8");
  const parsed = JSON.parse(raw);
  return parsed.elements || parsed.features || [];
}

/** যুক্তিসঙ্গত সীমা মুদ্রণ করে এবং সীমার বাইরে হলে থামে। */
function assertRange(name, value, min, max, label) {
  if (value < min || value > max) {
    throw new Error(`${name}: ${label} ${value} বেশি/কম — সীমা ${min}..${max} এর বাইরে`);
  }
}

function main() {
  const haramElements = loadOverpass("data/gates/haram-gates.overpass.json");
  const nabawiElements = loadOverpass("data/gates/nabawi-gates.overpass.json");

  const haramGates = extractGatesFromOverpass(haramElements, "haram");
  const nabawiGates = extractGatesFromOverpass(nabawiElements, "nabawi");
  const all = [...haramGates, ...nabawiGates];

  assertRange("haramGates", haramGates.length, 90, 170, "হ্যারাম গেট সংখ্যা");
  assertRange("nabawiGates", nabawiGates.length, 40, 80, "নববী গেট সংখ্যা");
  assertRange("total", all.length, 130, 250, "মোট গেট সংখ্যা");

  console.log(
    `গেট পাওয়া গেছে: হ্যারাম ${haramGates.length}, নববী ${nabawiGates.length}, মোট ${all.length}`
  );

  // --- উত্পন্ন TS ---
  const gatesJs = all.map((g) => toGate(g)).sort((a, b) => a.id.localeCompare(b.id));
  const tsBody =
    `${GENERATED_HEADER}\n\nimport type { Gate } from "@/types/gate";\n\n` +
    `export const GATES_OSM: Gate[] = ${JSON.stringify(gatesJs, null, 2)};\n`;
  writeFileSync(GENERATED_TS, tsBody);
  console.log("উত্পন্ন ডেটাসেট:", GENERATED_TS, `(${gatesJs.length} গেট)`);
}

try {
  main();
} catch (err) {
  console.error("গেট বিল্ড ব্যর্থ:", err.message);
  process.exit(1);
}
